name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn --frozen-lockfile
    - run: yarn test --coverage
    - name: Create coverage report flag
      id: codecov-flag
      run: echo "::set-output name=flag::node_${NODE_VERSION/./_}"
      env:
        NODE_VERSION: ${{ matrix.node-version }}
    - uses: codecov/codecov-action@v1
      with:
        flags: ${{ steps.codecov-flag.outputs.flag }}

